theme: jekyll-theme-minimal
title: Colby Snyder
logo: /assets/headshot_circle.png
description: >
  Hi! I’m Colby, a senior at UPenn pursuing dual Bachelor’s degrees in Chemical Engineering and Physics. I love clean energy, classical music, and camping. \n
  
  I've managed Li-ion cell development programs at Tesla, engineered materials for nuclear fusion reactors at CFS and General Atomics, and published peer-reviewed battery electrolyte research at Penn. \n
  
  Reach out by <a href="mailto:colbysny@seas.upenn.edu">email</a> or <a href="https://www.linkedin.com/in/colbysny/" target="_blank">LinkedIn</a> if you’d like to chat!





