title: Colby Snyder
logo: /assets/headshot_circle.png
description: >
  Chemical engineering, physics, and materials research @ UPenn <br>
  <a href="https://www.linkedin.com/in/colbysny/" target="_blank">Connect on LinkedIn</a>
theme: jekyll-theme-minimal

